### ISSUE TITLE
RDS 升级

### ISSUE THREAD

**Issue by fengmk2** [cnpm/npm.taobao.org#2]

**Comment by fengmk2** [comment]
http://help.aliyun.com/knowledge_detail.htm?spm=5176.788314899.3.1.xmhSuS&knowledgeId=5974579&categoryId=8314899

**Comment by fengmk2** [comment]
mysqldump -hxxxxx.mysql.rds.aliyuncs.com -uxxxx -p --opt --default-character-set=utf8 --hex-blob xxxx --skip-triggers > taobaonpm-2015-04-28-23.sql

**Comment by fengmk2** [comment]
mysql -hxxxxx.mysql.rds.aliyuncs.com -uxxxx -p xxxx < taobaonpm-2015-04-28-23.sql

**Comment by JacksonTian** [comment]
这个rds是你自己掏钱的还是赞助的？

**Comment by fengmk2** [comment]
嗯
