### ISSUE TITLE
An error of electron mirror source link

### ISSUE THREAD

**Issue by zce** [cnpm/npm.taobao.org#34]
## Example
- Bad
  - https://npm.taobao.org/mirrors/electron/1.2.7/ → https://github.com/atom/electron/releases/1.2.7/
- Good
  - https://npm.taobao.org/mirrors/electron/v1.2.7/ → https://github.com/atom/electron/releases/v1.2.7/

**Comment by fengmk2** [comment]
you can set mirror url as `https://npm.taobao.org/mirrors/electron/v`

**Comment by zce** [comment]
![s](https://cloud.githubusercontent.com/assets/6166576/16828675/997144f6-49c4-11e6-8f5a-6c26c9a884b4.png)

https://github.com/atom/electron/releases/[x.x.x]/ is not found

https://github.com/atom/electron/releases/v[x.x.x]/ is ok
