### ISSUE TITLE
关于 electron 安装源的问题

### ISSUE THREAD

**Issue by Cheonsoon** [cnpm/npm.taobao.org#35]
请教一下，我这样设置 registry 到国内镜像之后，
`alias tnpm="npm \
--registry=https://registry.npm.taobao.org \
--cache=$HOME/.tnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.tnpmrc \
--verbose"`
为什么其它的 modules 都是通过国内镜像下载的，但是 electron-prebuilt 始终会从 github 的 aws 上去 down 呢？
我查询过本地 electron-prebuilt 的 module meta ，下载地址也确实是国内镜像的地址。不知该怎么办好了。。

**Comment by fengmk2** [comment]
请先按照 cnpm，然后通过 cnpm i electron-prebuilt 来安装。
