### ISSUE TITLE
sync命令同步模块失败

### ISSUE THREAD

**Issue by infeng** [cnpm/npm.taobao.org#41]
今天我的一个模板发布了一个新版本，但是在npm.taobao.org上还是旧版本，用  `sync `同步了还是只有旧版本，想问一下这个问题怎么解决？

**Comment by fengmk2** [comment]
https://github.com/npm/registry/issues/70 问题在这里，已经临时修复。请重新 sync 同步一次即可。

**Comment by fengmk2** [comment]
https://npm.taobao.org/package/react-viewer 我同步了你的一个今天更新的模块，成功了。

**Comment by infeng** [comment]
thank you

**Comment by fengmk2** [comment]
模块名称是？

**Comment by infeng** [comment]
就是你说的react-viewer
