### ISSUE TITLE
npm使用淘宝的源 安装包巨慢

### ISSUE THREAD

**Issue by rolitter** [cnpm/npm.taobao.org#50]
![image](https://user-images.githubusercontent.com/27326998/31880377-e43c4e1e-b812-11e7-9342-b14e68bd012b.png)
安装包时间非常久
![image](https://user-images.githubusercontent.com/27326998/31880521-638226b2-b813-11e7-94bf-17d78d2d2730.png)
![image](https://user-images.githubusercontent.com/27326998/31880320-b58e7092-b812-11e7-9735-85688613d49b.png)
![image](https://user-images.githubusercontent.com/27326998/31880424-0d6ceba4-b813-11e7-96f0-4df87edd5f4b.png)

**Comment by fengmk2** [comment]
请使用 cnpm install webpack 试试，单单切换 registry 并不一定解决问题，依赖可能去任何网络资源请求数据。
