### ISSUE TITLE
taobao 源地址格式跟 npmjs 格式区别问题

### ISSUE THREAD

**Issue by chenyong** [cnpm/npm.taobao.org#62]
因为网络原因, 原先老的 `yarn.lock` 当中的链接期望能切换到 taobao npm 来, 但是根据
https://github.com/yarnpkg/yarn/issues/5892 的方案在替换 host 的时候发现路径不对

比如 yarn 安装的模块(带 scope)

```
https://registry.yarnpkg.com/@emotion/cache/-/cache-10.0.27.tgz
```

对应的 npmjs 地址

```
https://registry.npmjs.org/@emotion/cache/-/cache-10.0.27.tgz
```

直接替换域名, 得到:

```
https://registry.npm.taobao.org/@emotion/cache/-/cache-10.0.27.tgz
```
访问这个链接得到的是:

{
  "error": "[not_found] document not found",
  "reason": "[not_found] document not found"
}

参考可行的例子例子, 我在中间加上 scope, 现在地址当中有两个 @emotion, 就能得到对应的包了,

```
https://registry.npm.taobao.org/@emotion/cache/-/@emotion/cache-10.0.27.tgz
```

从方便迁移的角度, 需要 taobao 源对这个路径格式做一下兼容. 不然还是用脚本做专门的替换才能把老的 `yarn.lock` 迁移过来了.

**Comment by chenyong** [comment]
定义看着挺怪的 https://github.com/cnpm/cnpmjs.org/blob/master/routes/web.js#L19

**Comment by alienzj** [comment]
https://github.com/jupyterlab/jupyterlab/issues/8431

**Comment by atian25** [comment]
从方便迁移的角度，应该是写个脚本替换 lock 文件更快吧

**Comment by alienzj** [comment]
```python
with open("yarn.lock", encoding='utf-8') as f:
    count = 0
    for line in f:
        if "https://registry.npm.taobao.org" in line:
            count += 1
            line_list = line.split("/")
            line_list_ = line_list[0:6] + [line_list[3]] + line_list[6:]
            if count <= 20:
                print("/".join(line_list_))
```
